### ISSUE TITLE
[Debugger] When a method has #shouldBeImplemented it should allow to create a new one

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#124]
When there is a #houldBeImplemented, a ShouldBeImplemented error is signaled. 
It should be handled as a MNU or a SubclassResponsibility

**Comment by StevenCostiou** [comment]
Hi @tesonep I do not get the point: how should we create a new method?
For instance, if I get into a `ShouldBeImplemented`, we see the method in the debugger. I thought that the standard way was to implement it right here instead, not clicking the create button.
Are you referring to another usecase?

**Comment by StevenCostiou** [comment]
However, one thing that is maybe disrupting is that the should be implemented is not opened on the right method in the debugger. In that case (as for warnings, should not implement, etc.), the debugger opens on the method in `Object` that signals the exception instead of on the method that is concerned.

It is fixed by that PR https://github.com/pharo-project/pharo/pull/7714 if you can review it the current issue can be fixed right away. The PR is trivial (pragma added to a few methods in Object).

**Comment by guillep** [comment]
Usually the `shouldBeImplemented` is a marker method created by the TDD-related tooling.
The workflow is like this:
 - you write and run some code
 - the code fails in a DNU
 - You click on "create" 
     => you're asked in what class to create it
     => A marker method is created in that class (`yourSelector ^ self shouldBeImplemented`)
     => then execution is resumed and, if the class was correct, it will hit the shouldBeImplemented.
- At this point you have the opportunity to define your new method in the debugger

I think the PR is wrong, it will just forbid this kind of workflows.

I have the same feeling about many of the new features: the debugger tries to be too intelligent (it hides things, it disables buttons), and it actually forbids you to code in the debugger

**Comment by StevenCostiou** [comment]
@guillep I do not understand your comment nor how it is related.
This issue is about a "create" button when we hit a #shouldBeImplemented. I said that instead, when you hit it you do not need the create, you just have to code in the debugger. You are saying the same. The DNU (or any other way we got there) are not related.

It is not intentional to disrupt coding in the debugger. If you have cases, please let me know exactly. Up to know, it always was unwanted or unknown side effects that I fixed. 

However, there is value to hide mechanics that are irrelevant to developers (like signaling mechanics, for ex., in subclass responsibilities, etc.).

**Comment by guillep** [comment]
Yes, now that I see your screenshots I think it is ok! Thanks!
