### ISSUE TITLE
Inconsistent Halt receiver debugging

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/NewTools#140]
Not sure what to think about this and if it should be considered to be a bug. Try this:

1 ) install a method with `halt` into some class, `Announcer` in this case:
```
Announcer>>#hasSubscriptions

	self halt
```
2) if you run 
```smalltalk
Announcer new msg
```
you will get correct state with an announcer as the receiver
![Pharo_1lKvPeJPz9](https://user-images.githubusercontent.com/572494/101463806-2d8e7b00-393e-11eb-9a5c-8aea95b4223b.png)

3) if you do
```smalltalk
Announcer new halt
```
you will get nil as the receiver (because it is a receiver of the DoIt message)
![Pharo_GSOYjlOhyO](https://user-images.githubusercontent.com/572494/101464077-7c3c1500-393e-11eb-9d58-6eee171e1d49.png)

**Comment by pavel-krivanek** [comment]
What about to at least provide in context menu - stack an option to display a complete stack without filtering, I guess it may be useful in some other cases as well

**Comment by StevenCostiou** [comment]
I agree

**Comment by StevenCostiou** [comment]
So I did the following.

First, you now have a settings shortcut in the debugger (just above the stack):

![Screenshot 2021-01-27 at 09 17 06](https://user-images.githubusercontent.com/26929529/105962706-70d4b280-6080-11eb-96df-3c4f7049a7c1.png)

Then, you have a setting to tell if you want to filter or not:

![Screenshot 2021-01-27 at 09 17 36](https://user-images.githubusercontent.com/26929529/105962789-834eec00-6080-11eb-9589-c5666b0a9840.png)

You may still miss some methods because in some cases, I believe contexts with a `#debuggerCompleteToSender`method are completed. You also have to restart the debugger (no stack update). A simple update button could be put near the settings button.
