### ISSUE TITLE
Loading baseline fails in Pharo 7 (looking for FlagsBrowser)

### ISSUE THREAD

**Issue by jvalteren** [pharo-spec/NewTools#22]
Hi,

I would like to get the FlagsBrowser to go in Pharo 7. However, when I load the NewTools baseline in a fresh image, I get the warnings below (I left out duplicates).

```
1) This package depends on the following classes:
  CmCommand
  SpPresenter
  SpApplication

2) This package depends on the following classes:
  SpApplicationConfiguration

3) This package depends on the following classes:
  StPresenter
  CmCommand
  SpPresenter

4) This package depends on the following classes:
  SpecDebugger

5) This package depends on the following classes:
  StInspection
  CmCommand
```

I understand that the new Spec 2 development is taking place in Pharo 8 and this might be tightly coupled to that. However, most people working with Pharo professionally for clients will want to work with the latest stable version. Like me :-)

The 'old' FlagsBrowser doesn't work either, because it's missing some code related to a notebook (page).

What would be a good way to resolve this? Please advise.

Kind regards,
Jonathan

**Comment by estebanlm** [comment]
Not really. 
NewTools are meant to be made for Pharo 8 (Spec 2, Commander 2).
I understand you want to use the stable version, but then you cannot use *also* the unstable tools, I guess. 
Still, you may try to load Spec 2 first and NewTools later.
But installing current version of new tools will install SpecDebugger (you do not want that) and it will NOT install the flags browser (because loafing was failing and we deferred fixing it for next months). Instead, you may try to load it manually (is just a couple of packages after all).

No idea how this will work, as I said this is meant to work on P8, but it worths a try.

**Comment by jvalteren** [comment]
Hi @estebanlm, thanks for your comments. I started out by asking @jecisc about the FlagsBrowser in his personal repository, which doesn't work for different reasons. He pointed me in the direction of NewTools, but as you say, that's for P8 so unusable to me.
