### ISSUE TITLE
Spotter smoother flow

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#225]
Typing on enter should execute the first item on the list
Else we have to click with the mouse. 
For example here I typed everything and still if this is the class that I want I have to take the mouse to click on it. 

![Screenshot 2021-05-02 at 10 44 09](https://user-images.githubusercontent.com/432549/116807431-7e904d00-ab33-11eb-8545-e61605e93157.png)

**Comment by estebanlm** [comment]
In the next integration there will be a fix for this: it will execute the first element in the list *if that element matches exactly with what is in the search field*... which you will see because the element will be highlighted.
(I had some problems to record a gif, so you will need to watch it once integrated :P)
