### ISSUE TITLE
Debugger: Creating an unexisting method does not refresh the view when stack is unfiltered

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#489]
I think it's easier to show:

![Mar-16-2023 22-30-45](https://user-images.githubusercontent.com/9519971/225757354-4bfbbf56-24d7-42b2-a0f0-727105929f5b.gif)

After clicking on "Create" the text editor is not refreshed

**Comment by adri09070** [comment]
So, it doesn't update when you create the method and it updates when you perform "Cancel" ?

I haven't managed to reproduce it at my first try so I think I need more context.

I think that this bugs because you see the `#doesNotUnderstand:` context in the stack, which you aren't supposed to see, unless you clicked on the "a z" icon in the top right hand-corner.

Did you click on this icon ?

Anyway, it's interesting to discover that the debugger doesn't work well when this button is clicked
