### ISSUE TITLE
Random failure: testHaltOnCount

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#505]
This week we got two times a random failure of this test in Pharo CI:
testHaltOnCount – MacOSX64.Debugging.Utils.Tests.HaltTest

Here is the stack trace:

```
Error
Assertion failed
Stacktrace
TestFailure
Assertion failed
HaltTest(TestAsserter)>>assert:description:resumable:
HaltTest(TestAsserter)>>assert:description:
HaltTest(Object)>>assert:
HaltTest(TestAsserter)>>should:raise:
HaltTest>>shouldHaltWhen:
HaltTest>>shouldHaltAfter:times:
HaltTest>>testHaltOnCount
HaltTest(TestCase)>>performTest
```

**Comment by jecisc** [comment]
The failure is not only on this test. See: https://github.com/pharo-project/pharo/issues/13451

This one is on one of the other tests

**Comment by PalumboN** [comment]
To reproduce it, you can 

1. Execute the test -> OK
2. Debug the test and execute -> OK
3. Execute the test again -> FAIL

We were looking w/ @guillep and the problem seems to be related to the breakpoint (instrumentation) inserted for debugging. It changes the PCs of the nodes inside the method. Then, a cache is keeping info related to the instrumented method and tries to use it with the "normal" version. So... PUM

We could fix it but then the `haltOnCount:` is not working as expected (not restarting the count).

**Comment by adri09070** [comment]
Actually, 

> To reproduce it, you can
> 
> 1. Execute the test -> OK
> 2. Debug the test and execute -> OK
> 3. Execute the test again -> FAIL

I noticed that too. But actually, if you look closer at the stack, you don't get the **exact** same error. You get another one.

> We were looking w/ @guillep and the problem seems to be related to the breakpoint (instrumentation) inserted for debugging. 

It was my guess too but couldn't come up with an explanation

> It changes the PCs of the nodes inside the method.  Then, a cache is keeping info related to the instrumented method and tries to use it with the "normal" version. So... PUM
> 
> We could fix it but then the `haltOnCount:` is not working as expected (not restarting the count).

**Comment by PalumboN** [comment]
Okk! I will push what I have and we can check the failure (about restarting the count) in another issue

**Comment by PalumboN** [comment]
We found the problem and a fix with @uNouss :)

It is explained in the PR: https://github.com/pharo-project/pharo/pull/14167
