### ISSUE TITLE
Context inspector tries to be too smart 

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#82]
The inspector of a context should show the interpreted values (temps, receiver, etc) and also it should correctly show everything in the raw tab (method, pc, stack, home, blockOrNil, ......)

**Comment by StevenCostiou** [comment]
Hi Pablo, do you mean in the inspector or in the debugger ? (or both?)

**Comment by guillep** [comment]
His machine got a heart attack. So I answer here for him. The raw view is really not raw. It does not show all the internals of the contexts (like method, pc...).

We understand that a higher level view is nice for most users, but from time to time you need the raw.

So I think that either we need several tabs (real raw and the high level one). Maybe RAW could not be the default one.

In short, we needed to access the bytecode and other info of the current context either by inspecting or evaluating something, and it was not possible.

**Comment by StevenCostiou** [comment]
Ah, yes I see.
There was a context inspection (just another tab).
It is not difficult to add, I will try to find it back (except if Esteban had plans).

**Comment by estebanlm** [comment]
nope. if it is not there, is because I missed it :)

**Comment by StevenCostiou** [comment]
I think the inspector is fine, but the problem is in the raw view of the debugger inspector.
- I added thisContext node (we'll see later how to provide simpler views for lambda users but I think it is good to always have the context)
- The inspector does not show the bytecode: there a special inspection needs to be built in methods and contexts (but this is another issue)
