### ISSUE TITLE
Inspector is super slow when inspecting variables in blocks

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/NewTools#96]
To reproduce:
- step through a block with arguments
- while in the block, select different variables in the bottom inspector
There is a latency for the inspector pane to open on the selected object.
It seems that depending on the block (?) the latency is more or less strong.

**Comment by MarcusDenker** [comment]
If we look at that:

`tempNodesForContext: aContext
	^ aContext tempNames collect: [ :name | 
		  (StInspectorTempNode hostObject: aContext) tempVariable:
			  (aContext temporaryVariableNamed: name) ]
`


#tempNames calls #allTempNames on the scope:

`
allTempNames
	^self allTemps collect: [: each | each name]

`
so that means we had the temps already in hand, but just got the names, to then take the names to make an object again.

So I think we can just write:

`
tempNodesForContext: aContext
	^ aContext astScope allTemps collect: [ :temp | 
		  (StInspectorTempNode hostObject: aContext) tempVariable: temp]
`

**Comment by adri09070** [comment]
I don't feel any latency right now. I think this issue should be closed

**Comment by MarcusDenker** [comment]
I think the fix that I did really helped there
